/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author l3huz
 */

import java.awt.Color;
import java.util.List;

public class TelaDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDashboard.class.getName());

    /**
     * Creates new form TelaDashboard
     */
    public TelaDashboard() {
        initComponents();
        configurarDashboard();
        this.setLocationRelativeTo(null);
    }
    
    private void configurarDashboard() {
        // 1. BOAS VINDAS
        if (DadosTemporarios.usuarioLogado != null) {
            // Pega o nome do usuário logado
            lblUsuario.setText("Bem-vindo, " + DadosTemporarios.usuarioLogado.getNome() + "!");
        }

        // 2. CONTAGEM DE DADOS
        int qtdColecoes = 0;
        int totalJogos = 0;

        // Varre todas as coleções do sistema
        for (Colecao c : DadosTemporarios.listaColecoes) {
            // Filtra apenas as do usuário logado
            if (c.getUsuario() == DadosTemporarios.usuarioLogado) {
                qtdColecoes++; // Conta +1 coleção
                totalJogos += c.getListaJogos().size(); // Soma os jogos dessa coleção
            }
        }

        // Atualiza os Labels
        lblQtdColecoes.setText(String.valueOf(qtdColecoes));
        lblTotalJogos.setText(String.valueOf(totalJogos)); // Verifique se o nome é lblTotalJogos ou lblQtdJogos
        
        // 3. ÚLTIMO JOGO CADASTRADO
        lblUltimoJogo.setText(DadosTemporarios.usuarioLogado.getUltimoJogoCadastrado());
        
        // 4. ACESSO RÁPIDO (Botões)
        configurarBotoesAcessoRapido();
    }
    
    private void configurarBotoesAcessoRapido() {
        List<String> historico = DadosTemporarios.usuarioLogado.getHistoricoAcesso();
        
        // Reset visual dos botões (caso não tenha histórico)
        btnAcessoRapido1.setText("---");
        btnAcessoRapido1.setEnabled(false);
        
        btnAcessoRapido2.setText("---");
        btnAcessoRapido2.setEnabled(false);

        // BOTÃO 1 (Última acessada - Índice 0)
        if (historico.size() >= 1) {
            String nomeCol1 = historico.get(0);
            // Verifica se a coleção ainda existe (caso tenha sido excluída em algum momento futuro)
            if (existeColecao(nomeCol1)) {
                btnAcessoRapido1.setText(nomeCol1);
                btnAcessoRapido1.setEnabled(true);
            }
        }

        // BOTÃO 2 (Penúltima acessada - Índice 1)
        if (historico.size() >= 2) {
            String nomeCol2 = historico.get(1);
            if (existeColecao(nomeCol2)) {
                btnAcessoRapido2.setText(nomeCol2);
                btnAcessoRapido2.setEnabled(true);
            }
        }
    }
    
    // Método auxiliar para verificar se coleção existe do usuário logado
    private boolean existeColecao(String nome) {
        for (Colecao c : DadosTemporarios.listaColecoes) {
            if (c.getNome().equals(nome) && c.getUsuario() == DadosTemporarios.usuarioLogado) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenuInicio = new javax.swing.JButton();
        btnMenuColecoes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblQtdColecoes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblTotalJogos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblUltimoJogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAcessoRapido2 = new javax.swing.JButton();
        btnAcessoRapido1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(18, 18, 18));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(30, 30, 30));

        btnMenuInicio.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuInicio.setText("INÍCIO");
        btnMenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuInicioActionPerformed(evt);
            }
        });

        btnMenuColecoes.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuColecoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuColecoes.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuColecoes.setText("COLEÇÕES");
        btnMenuColecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuColecoesActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(0, 230, 118));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 770));

        jPanel2.setBackground(new java.awt.Color(30, 30, 30));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Bem-vindo, Usuário");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total de Coleções:");

        lblQtdColecoes.setBackground(new java.awt.Color(0, 230, 118));
        lblQtdColecoes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQtdColecoes.setForeground(new java.awt.Color(0, 230, 118));
        lblQtdColecoes.setText("XXXX");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQtdColecoes)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblQtdColecoes))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 115, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total de Jogos:");

        lblTotalJogos.setBackground(new java.awt.Color(0, 230, 118));
        lblTotalJogos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalJogos.setForeground(new java.awt.Color(0, 230, 118));
        lblTotalJogos.setText("XXXX");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalJogos)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotalJogos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 115, -1, 68));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Último Jogo Adicionado:");

        lblUltimoJogo.setBackground(new java.awt.Color(0, 230, 118));
        lblUltimoJogo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUltimoJogo.setForeground(new java.awt.Color(0, 230, 118));
        lblUltimoJogo.setText("Nome do jogo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUltimoJogo)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblUltimoJogo))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 201, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Acesso Rápido");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 308, -1, -1));

        btnAcessoRapido2.setBackground(new java.awt.Color(0, 230, 118));
        btnAcessoRapido2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAcessoRapido2.setText("JOGOS DE PS4");
        btnAcessoRapido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessoRapido2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAcessoRapido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 470, 324, 84));

        btnAcessoRapido1.setBackground(new java.awt.Color(0, 230, 118));
        btnAcessoRapido1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAcessoRapido1.setText("JOGOS DE PC");
        btnAcessoRapido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessoRapido1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAcessoRapido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 368, 324, 84));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 850, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInicioActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Você já esta aqui!");
    }//GEN-LAST:event_btnMenuInicioActionPerformed

    private void btnMenuColecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuColecoesActionPerformed
        new TelaColecoes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuColecoesActionPerformed

    private void btnAcessoRapido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessoRapido1ActionPerformed
        String nomeColecao = btnAcessoRapido1.getText();
        new TelaListaJogos(nomeColecao).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAcessoRapido1ActionPerformed

    private void btnAcessoRapido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessoRapido2ActionPerformed
        String nomeColecao = btnAcessoRapido2.getText();
        new TelaListaJogos(nomeColecao).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAcessoRapido2ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // 1. Limpa o usuário da memória (Logout)
        DadosTemporarios.usuarioLogado = null;
        
        // 2. Volta para a tela de Login
        new TelaLogin().setVisible(true);
        
        // 3. Fecha a tela atual
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessoRapido1;
    private javax.swing.JButton btnAcessoRapido2;
    private javax.swing.JButton btnMenuColecoes;
    private javax.swing.JButton btnMenuInicio;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblQtdColecoes;
    private javax.swing.JLabel lblTotalJogos;
    private javax.swing.JLabel lblUltimoJogo;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
