/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author l3huz
 */

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.JOptionPane;

public class TelaColecoes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaColecoes.class.getName());

    /**
     * Creates new form TelaColecoes
     */
    public TelaColecoes() {
        initComponents();
        carregarColecoesDinamicas();
        this.setLocationRelativeTo(null);
    }
    
    private void carregarColecoesDinamicas() {
        // Limpa qualquer coisa que esteja no painel (para não duplicar)
        pnlContainerCards.removeAll();

        // Verifica se a lista está vazia
        if (DadosTemporarios.listaColecoes.isEmpty()) {
            // Opcional: Mostrar uma mensagem ou label dizendo "Nenhuma coleção"
        }

        // PERCORRE A LISTA REAL DE COLEÇÕES
        for (Colecao c : DadosTemporarios.listaColecoes) {
            // Verifica se a coleção pertence ao usuário logado (opcional, mas bom pra lógica)
            if (c.getUsuario() == DadosTemporarios.usuarioLogado) {
                // Chama o criador de card passando os dados reais
                criarCardColecao(c.getNome(), c.getIcone(), c.getListaJogos().size());
            }
        }

        // Atualiza a tela
        pnlContainerCards.revalidate();
        pnlContainerCards.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenuInicio = new javax.swing.JButton();
        btnMenuColecoes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCriarColecao = new javax.swing.JButton();
        pnlContainerCards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(30, 30, 30));

        btnMenuInicio.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuInicio.setText("INÍCIO");
        btnMenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuInicioActionPerformed(evt);
            }
        });

        btnMenuColecoes.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuColecoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuColecoes.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuColecoes.setText("COLEÇÕES");
        btnMenuColecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuColecoesActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(0, 230, 118));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 770));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Minhas Coleções");

        btnCriarColecao.setBackground(new java.awt.Color(0, 230, 118));
        btnCriarColecao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCriarColecao.setText("Criar Nova");
        btnCriarColecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarColecaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 498, Short.MAX_VALUE)
                .addComponent(btnCriarColecao, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCriarColecao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 850, -1));

        pnlContainerCards.setBackground(new java.awt.Color(30, 30, 30));
        pnlContainerCards.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlContainerCards.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 30));
        getContentPane().add(pnlContainerCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 850, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInicioActionPerformed
        new TelaDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuInicioActionPerformed

    private void btnMenuColecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuColecoesActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Você já esta aqui!");
    }//GEN-LAST:event_btnMenuColecoesActionPerformed

    private void btnCriarColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarColecaoActionPerformed
       new TelaCriarColecao().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnCriarColecaoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // 1. Limpa o usuário da memória (Logout)
        DadosTemporarios.usuarioLogado = null;
        
        // 2. Volta para a tela de Login
        new TelaLogin().setVisible(true);
        
        // 3. Fecha a tela atual
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaColecoes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarColecao;
    private javax.swing.JButton btnMenuColecoes;
    private javax.swing.JButton btnMenuInicio;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlContainerCards;
    // End of variables declaration//GEN-END:variables

// Cores
    private final Color COR_CARD = new Color(51, 51, 51);
    private final Color COR_VERDE_NEON = new Color(0, 230, 118); // #00E676

    // Método que cria um card visualmente e o adiciona ao container
    private void criarCardColecao(String nomeColecao, String nomeIcone, int qtdItens) {
        // 1. O Fundo do Card
        JPanel card = new JPanel();
        card.setPreferredSize(new Dimension(200, 200));
        card.setBackground(COR_CARD);
        card.setLayout(null);

        // Ação de clique
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TelaListaJogos lista = new TelaListaJogos(nomeColecao); 
                lista.setVisible(true);
                dispose();
            }
        });

        // 2. O Ícone (Quadrado Verde)
        JPanel iconPanel = new JPanel();
        iconPanel.setBounds(75, 30, 50, 50);
        iconPanel.setBackground(COR_VERDE_NEON);
        
        // --- TRUQUE VISUAL ---
        // Vamos colocar a sigla ou nome do ícone dentro do quadrado verde
        JLabel lblIconeTexto = new JLabel(nomeIcone);
        if(nomeIcone.length() > 3) lblIconeTexto.setText(nomeIcone.substring(0, 2).toUpperCase()); // Pega só as 2 primeiras letras
        lblIconeTexto.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblIconeTexto.setForeground(Color.WHITE); // Texto branco no fundo verde
        iconPanel.add(lblIconeTexto); // Adiciona a letra no quadrado verde
        // ---------------------
        
        card.add(iconPanel);

        // 3. O Nome da Coleção
        JLabel lblNome = new JLabel(nomeColecao, SwingConstants.CENTER);
        lblNome.setForeground(Color.WHITE);
        lblNome.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblNome.setBounds(10, 110, 180, 20);
        card.add(lblNome);

        // 4. A Quantidade
        JLabel lblQtd = new JLabel(qtdItens + " jogos", SwingConstants.CENTER);
        lblQtd.setForeground(Color.LIGHT_GRAY);
        lblQtd.setBounds(10, 135, 180, 20);
        card.add(lblQtd);

        // 5. Adiciona ao painel
        pnlContainerCards.add(card);
    }
}
