/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author l3huz
 */
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.util.List;

public class TelaListaJogos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaListaJogos.class.getName());

    /**
     * Creates new form TelaListaJogos
     */
    private String nomeColecaoAtual;

    private void configurarTabelaJogos() {
        // 1. Cores do Corpo da Tabela
        tabelaJogos.setBackground(new Color(30, 30, 30)); // Fundo Cinza Escuro
        tabelaJogos.setForeground(Color.WHITE);           // Letra Branca
        tabelaJogos.setFont(new Font("Segoe UI", Font.PLAIN, 14)); // Letra maior
        tabelaJogos.setRowHeight(30);
        
        // 1.1 Cores do Cabeçalho (Header)
        javax.swing.table.JTableHeader header = tabelaJogos.getTableHeader();
        header.setBackground(new Color(0, 230, 118)); // Verde Neon
        header.setForeground(Color.BLACK);            // Letra Preta (Contraste Máximo)
        header.setFont(new Font("Segoe UI", Font.BOLD, 14)); // Negrito
        header.setBorder(javax.swing.BorderFactory.createEmptyBorder()); 
        
        // 1.2 Cor da área vazia do scroll
        scrollPaneTabela.getViewport().setBackground(new Color(30, 30, 30));

        // 2. Definir Colunas (Ajustado para os dados que temos no objeto Jogo)
        String[] colunas = {"Nome", "Ano", "Dev", "Gênero", "Mídia"};
    
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(colunas);
        modelo.setRowCount(0);

        // 3. BUSCAR DADOS REAIS
        // Primeiro, limpa a tabela
        modelo.setRowCount(0);

        // Procura a coleção certa na memória
        Colecao colecaoEncontrada = null;
        for (Colecao c : DadosTemporarios.listaColecoes) {
            // Verifica se o nome bate E se pertence ao usuário logado
            if (c.getNome().equals(this.nomeColecaoAtual) && c.getUsuario() == DadosTemporarios.usuarioLogado) {
                colecaoEncontrada = c;
                break;
            }
        }

        // Se achou a coleção, adiciona os jogos dela na tabela
        if (colecaoEncontrada != null) {
            for (Jogo jogo : colecaoEncontrada.getListaJogos()) {
            modelo.addRow(new Object[]{
                jogo.getNome(),
                jogo.getDataLancamento(),
                jogo.getDesenvolvedora().getNome(),
                jogo.getGenero(),
                jogo.getTipoMidia()
            });
            }
        } else {
            System.out.println("Coleção não encontrada ou vazia.");
        }
    
        // 4. Aplica o modelo na JTable
        tabelaJogos.setModel(modelo);
    }

    //Construtor
    public TelaListaJogos(String nomeColecao) {
        initComponents();
        this.nomeColecaoAtual = nomeColecao; 
        lblNomeColecao.setText(nomeColecao); 
        configurarTabelaJogos();
        
        List<String> historico = DadosTemporarios.usuarioLogado.getHistoricoAcesso();
        historico.remove(nomeColecao);
        historico.add(0, nomeColecao);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent e) {
                configurarTabelaJogos();
            }
        });
        
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenuInicio = new javax.swing.JButton();
        btnMenuColecoes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNomeColecao = new javax.swing.JLabel();
        btnAdicionarJogo = new javax.swing.JButton();
        btnExcluirJogo = new javax.swing.JButton();
        btnEditarJogo = new javax.swing.JButton();
        scrollPaneTabela = new javax.swing.JScrollPane();
        tabelaJogos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(30, 30, 30));

        btnMenuInicio.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuInicio.setText("INÍCIO");
        btnMenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuInicioActionPerformed(evt);
            }
        });

        btnMenuColecoes.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuColecoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuColecoes.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuColecoes.setText("COLEÇÕES");
        btnMenuColecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuColecoesActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(0, 230, 118));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 770));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        lblNomeColecao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNomeColecao.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeColecao.setText("(Nome da coleção)");

        btnAdicionarJogo.setBackground(new java.awt.Color(0, 230, 118));
        btnAdicionarJogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdicionarJogo.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarJogo.setText("ADICIONAR JOGO");
        btnAdicionarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarJogoActionPerformed(evt);
            }
        });

        btnExcluirJogo.setBackground(new java.awt.Color(51, 51, 51));
        btnExcluirJogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExcluirJogo.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirJogo.setText("EXCLUIR JOGO");
        btnExcluirJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirJogoActionPerformed(evt);
            }
        });

        btnEditarJogo.setBackground(new java.awt.Color(0, 230, 118));
        btnEditarJogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarJogo.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarJogo.setText("EDITAR JOGO");
        btnEditarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblNomeColecao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnExcluirJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdicionarJogo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeColecao)
                    .addComponent(btnAdicionarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 850, -1));

        scrollPaneTabela.setBackground(new java.awt.Color(30, 30, 30));
        scrollPaneTabela.setForeground(new java.awt.Color(255, 255, 255));

        tabelaJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneTabela.setViewportView(tabelaJogos);

        getContentPane().add(scrollPaneTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 850, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInicioActionPerformed
        new TelaDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuInicioActionPerformed

    private void btnMenuColecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuColecoesActionPerformed
        new TelaColecoes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuColecoesActionPerformed

    private void btnAdicionarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarJogoActionPerformed
        new TelaCadastroJogo(this.nomeColecaoAtual).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdicionarJogoActionPerformed

    private void btnExcluirJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirJogoActionPerformed
        // 1. Verifica qual linha está selecionada
        int linhaSelecionada = tabelaJogos.getSelectedRow();
    
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um jogo na tabela para excluir.");
            return;
        }

        // 2. Confirmação
        int resposta = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este jogo?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
    
        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
        
            // 3. Busca a coleção atual
            for (Colecao c : DadosTemporarios.listaColecoes) {
                if (c.getNome().equals(this.nomeColecaoAtual) && c.getUsuario() == DadosTemporarios.usuarioLogado) {
                
                    // 4. Remove o jogo da lista (Baseado no índice da tabela)
                    c.getListaJogos().remove(linhaSelecionada);
                
                    // 5. Atualiza a tabela
                    configurarTabelaJogos();
                    javax.swing.JOptionPane.showMessageDialog(this, "Jogo excluído!");
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnExcluirJogoActionPerformed

    private void btnEditarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarJogoActionPerformed
        int linhaSelecionada = tabelaJogos.getSelectedRow();
    
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um jogo para editar.");
            return;
        }

        // Encontra o objeto Jogo real na lista
        Jogo jogoParaEditar = null;
        for (Colecao c : DadosTemporarios.listaColecoes) {
            if (c.getNome().equals(this.nomeColecaoAtual) && c.getUsuario() == DadosTemporarios.usuarioLogado) {
                jogoParaEditar = c.getListaJogos().get(linhaSelecionada);
                break;
            }
        }

        if (jogoParaEditar != null) {      
            TelaEditarJogo telaEdicao = new TelaEditarJogo(jogoParaEditar);
            telaEdicao.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarJogoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // 1. Limpa o usuário da memória (Logout)
        DadosTemporarios.usuarioLogado = null;
        
        // 2. Volta para a tela de Login
        new TelaLogin().setVisible(true);
        
        // 3. Fecha a tela atual
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaListaJogos("TESTE DE FLUXO").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarJogo;
    private javax.swing.JButton btnEditarJogo;
    private javax.swing.JButton btnExcluirJogo;
    private javax.swing.JButton btnMenuColecoes;
    private javax.swing.JButton btnMenuInicio;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNomeColecao;
    private javax.swing.JScrollPane scrollPaneTabela;
    private javax.swing.JTable tabelaJogos;
    // End of variables declaration//GEN-END:variables
}
