/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author l3huz
 */
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Font;

public class TelaListaJogos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaListaJogos.class.getName());

    /**
     * Creates new form TelaListaJogos
     */
    // Cores
    private final Color COR_HEADER_TABELA = new Color(30, 30, 30); // Cinza Chumbo
    private final Color COR_TEXTO_BRANCO = Color.WHITE;
    private final Color COR_VERDE_NEON = new Color(0, 230, 118);

    private void configurarTabelaJogos() {
        // 1. Definir as colunas da tabela
        Object[] colunas = {"Capa", "Nome", "Ano", "Gênero", "Ações"}; // Nomes do seu Figma

        // 2. Simular dados
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(colunas);

        // Dados de exemplo (Mock Data)
        Object[][] dados = {
            {"[Capa]", "God of War", "2018", "Ação", "[Editar/Excluir]"},
            {"[Capa]", "The Last of Us", "2013", "Aventura", "[Editar/Excluir]"},
            {"[Capa]", "Doom Eternal", "2020", "FPS", "[Editar/Excluir]"}
        };

        for (Object[] linha : dados) {
            modelo.addRow(linha);
        }
    
        // 3. Aplicar o modelo na JTable
        tabelaJogos.setModel(modelo);

        // 4. Estilizar o cabeçalho (Para ficar Dark Mode)
        tabelaJogos.setBackground(new Color(18, 18, 18)); // Fundo da tabela: Preto
        tabelaJogos.setForeground(COR_TEXTO_BRANCO); // Cor do texto da tabela: Branco
    
        // Configura a cor do cabeçalho
        tabelaJogos.getTableHeader().setBackground(COR_HEADER_TABELA);
        tabelaJogos.getTableHeader().setForeground(COR_TEXTO_BRANCO);
    
        // Estilo da barra de rolagem (opcional, mas melhora a visualizacao)
        scrollPaneTabela.getViewport().setBackground(new Color(18, 18, 18)); 
    }

// Chame no construtor:
public TelaListaJogos(String nomeColecao) {
    initComponents();
    
    // 1. ATUALIZA o texto do cabeçalho com o nome da coleção
    lblNomeColecao.setText(nomeColecao); 
    
    // 2. Configura a tabela
    configurarTabelaJogos();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenuInicio = new javax.swing.JButton();
        btnMenuColecoes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNomeColecao = new javax.swing.JLabel();
        btnAdicionarJogo = new javax.swing.JButton();
        scrollPaneTabela = new javax.swing.JScrollPane();
        tabelaJogos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(30, 30, 30));

        btnMenuInicio.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuInicio.setText("INÍCIO");
        btnMenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuInicioActionPerformed(evt);
            }
        });

        btnMenuColecoes.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuColecoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuColecoes.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuColecoes.setText("COLEÇÕES");
        btnMenuColecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuColecoesActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(0, 230, 118));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 770));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        lblNomeColecao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNomeColecao.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeColecao.setText("(Nome da coleção)");

        btnAdicionarJogo.setBackground(new java.awt.Color(0, 230, 118));
        btnAdicionarJogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdicionarJogo.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarJogo.setText("Adicionar Jogo");
        btnAdicionarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarJogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblNomeColecao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addComponent(btnAdicionarJogo)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeColecao)
                    .addComponent(btnAdicionarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 850, -1));

        tabelaJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneTabela.setViewportView(tabelaJogos);

        getContentPane().add(scrollPaneTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 850, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInicioActionPerformed
        new TelaDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuInicioActionPerformed

    private void btnMenuColecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuColecoesActionPerformed
        new TelaColecoes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuColecoesActionPerformed

    private void btnAdicionarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarJogoActionPerformed
        new TelaCadastroJogo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdicionarJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaListaJogos("TESTE DE FLUXO").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarJogo;
    private javax.swing.JButton btnMenuColecoes;
    private javax.swing.JButton btnMenuInicio;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNomeColecao;
    private javax.swing.JScrollPane scrollPaneTabela;
    private javax.swing.JTable tabelaJogos;
    // End of variables declaration//GEN-END:variables
}
