package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author l3huz
 */
import util.DadosTemporarios;
import dao.JogoDAO;
import dao.ColecaoDAO;
import model.Colecao;
import model.Jogo;
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.util.List;

public class TelaListaJogos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaListaJogos.class.getName());

    /**
     * Creates new form TelaListaJogos
     */
    private List<Jogo> listaJogosAtual;
    private String nomeColecaoAtual;

    private void configurarTabelaJogos() {
        // A. Configuração Visual
        tabelaJogos.setBackground(new Color(30, 30, 30));
        tabelaJogos.setForeground(Color.WHITE);
        tabelaJogos.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tabelaJogos.setRowHeight(30);
        
        javax.swing.table.JTableHeader header = tabelaJogos.getTableHeader();
        header.setBackground(new Color(0, 230, 118));
        header.setForeground(Color.BLACK);
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
        
        scrollPaneTabela.getViewport().setBackground(new Color(30, 30, 30));

        // B. Define as Colunas
        String[] colunas = {"Nome", "Lançamento", "Dev", "Gênero", "Mídia"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0) {
            @Override 
            public boolean isCellEditable(int row, int column) { return false; }
        };
        
        tabelaJogos.setModel(modelo);
        
        // C. Carrega os dados iniciais (sem filtro)
        carregarJogos(""); 
    }
    
    private void carregarJogos(String filtro) {
        // 1. Limpa a tabela visual
        DefaultTableModel modelo = (DefaultTableModel) tabelaJogos.getModel();
        modelo.setRowCount(0);
        
        // 2. Descobre o ID da coleção atual
        int idColecao = -1;
        ColecaoDAO colDao = new ColecaoDAO();
        
        if (DadosTemporarios.usuarioLogado != null) {
            List<Colecao> colecoes = colDao.listarPorUsuario(DadosTemporarios.usuarioLogado.getId());
            for (Colecao c : colecoes) {
                if (c.getNome().equals(this.nomeColecaoAtual)) {
                    idColecao = c.getId();
                    break;
                }
            }
        }
        
        if (idColecao == -1) return; // Segurança

        // 3. Busca no Banco (com ou sem filtro)
        JogoDAO dao = new JogoDAO();
        
        if (filtro == null || filtro.trim().isEmpty()) {
            // Se não tem filtro, busca tudo da coleção
            this.listaJogosAtual = dao.listarPorColecao(idColecao); 
        } else {
            // Se tem texto digitado, usa o método de pesquisa (LIKE)
            this.listaJogosAtual = dao.pesquisarPorNome(idColecao, filtro); 
        }
        
        // 4. Preenche a tabela visual
        for (Jogo j : this.listaJogosAtual) {
            modelo.addRow(new Object[]{
                j.getNome(),
                j.getDataLancamento(), // Ou j.getAno() se tiver mudado
                j.getDesenvolvedora().getNome(),
                j.getGenero(),
                j.getTipoMidia()
            });
        }
    }

    //Construtor
    public TelaListaJogos(String nomeColecao) {
        initComponents();
        this.nomeColecaoAtual = nomeColecao; 
        lblNomeColecao.setText(nomeColecao); 
        configurarTabelaJogos();
        
        List<String> historico = DadosTemporarios.usuarioLogado.getHistoricoAcesso();
        historico.remove(nomeColecao);
        historico.add(0, nomeColecao);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent e) {
                configurarTabelaJogos();
            }
        });
        
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenuInicio = new javax.swing.JButton();
        btnMenuColecoes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNomeColecao = new javax.swing.JLabel();
        btnAdicionarJogo = new javax.swing.JButton();
        btnExcluirJogo = new javax.swing.JButton();
        btnEditarJogo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        scrollPaneTabela = new javax.swing.JScrollPane();
        tabelaJogos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(30, 30, 30));

        btnMenuInicio.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuInicio.setText("INÍCIO");
        btnMenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuInicioActionPerformed(evt);
            }
        });

        btnMenuColecoes.setBackground(new java.awt.Color(51, 51, 51));
        btnMenuColecoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuColecoes.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuColecoes.setText("COLEÇÕES");
        btnMenuColecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuColecoesActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(0, 230, 118));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnMenuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 770));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeColecao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNomeColecao.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeColecao.setText("(Nome da coleção)");
        jPanel2.add(lblNomeColecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 30, -1, -1));

        btnAdicionarJogo.setBackground(new java.awt.Color(0, 230, 118));
        btnAdicionarJogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdicionarJogo.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarJogo.setText("ADICIONAR JOGO");
        btnAdicionarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarJogoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdicionarJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 6, -1, 55));

        btnExcluirJogo.setBackground(new java.awt.Color(51, 51, 51));
        btnExcluirJogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExcluirJogo.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirJogo.setText("EXCLUIR JOGO");
        btnExcluirJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirJogoActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcluirJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 6, 165, 55));

        btnEditarJogo.setBackground(new java.awt.Color(0, 230, 118));
        btnEditarJogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarJogo.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarJogo.setText("EDITAR JOGO");
        btnEditarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarJogoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditarJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 6, 165, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisar:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 68, -1, -1));

        txtPesquisa.setBackground(new java.awt.Color(220, 220, 220));
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        jPanel2.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 68, 445, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 850, 110));

        scrollPaneTabela.setBackground(new java.awt.Color(30, 30, 30));
        scrollPaneTabela.setForeground(new java.awt.Color(255, 255, 255));

        tabelaJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneTabela.setViewportView(tabelaJogos);

        getContentPane().add(scrollPaneTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 850, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInicioActionPerformed
        new TelaDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuInicioActionPerformed

    private void btnMenuColecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuColecoesActionPerformed
        new TelaColecoes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuColecoesActionPerformed

    private void btnAdicionarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarJogoActionPerformed
        new TelaCadastroJogo(this.nomeColecaoAtual).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdicionarJogoActionPerformed

    private void btnExcluirJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirJogoActionPerformed
        int linha = tabelaJogos.getSelectedRow();
        
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um jogo para excluir.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza?", "Excluir", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            // Pega o objeto Jogo da nossa lista usando o índice da tabela
            Jogo jogoAlvo = this.listaJogosAtual.get(linha);
            
            // Chama o DAO para excluir do Banco
            JogoDAO dao = new JogoDAO();
            dao.excluir(jogoAlvo.getId());
            
            JOptionPane.showMessageDialog(this, "Jogo excluído!");
            
            // Atualiza a tabela mantendo o filtro se houver algo escrito
            carregarJogos(txtPesquisa.getText());
        }
    }//GEN-LAST:event_btnExcluirJogoActionPerformed

    private void btnEditarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarJogoActionPerformed
        int linha = tabelaJogos.getSelectedRow();
        
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um jogo para editar.");
            return;
        }
        
        // Pega o jogo da lista carregada do banco
        Jogo jogoParaEditar = this.listaJogosAtual.get(linha);
        
        // Abre a tela de edição passando o objeto real
        TelaEditarJogo tela = new TelaEditarJogo(jogoParaEditar);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditarJogoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // 1. Limpa o usuário da memória (Logout)
        DadosTemporarios.usuarioLogado = null;
        
        // 2. Volta para a tela de Login
        new TelaLogin().setVisible(true);
        
        // 3. Fecha a tela atual
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        String termo = txtPesquisa.getText();
        carregarJogos(termo);
    }//GEN-LAST:event_txtPesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaListaJogos("TESTE DE FLUXO").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarJogo;
    private javax.swing.JButton btnEditarJogo;
    private javax.swing.JButton btnExcluirJogo;
    private javax.swing.JButton btnMenuColecoes;
    private javax.swing.JButton btnMenuInicio;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNomeColecao;
    private javax.swing.JScrollPane scrollPaneTabela;
    private javax.swing.JTable tabelaJogos;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
